let
    // Defina as datas de início e fim
    StartDate = #date(2020, 1, 1), // Altere conforme necessário
    EndDate = #date(2030, 12, 31), // Altere conforme necessário
    
    // Crie uma lista de datas
    Dates = List.Dates(StartDate, Duration.Days(EndDate - StartDate) + 1, #duration(1, 0, 0, 0)),
    
    // Transforme a lista em uma tabela
    DateTable = Table.FromList(Dates, Splitter.SplitByNothing(), {"Data"}),
    
    // Adicione colunas adicionais
    DateWithColumns = Table.TransformColumnTypes(DateTable, {{"Data", type date}}),
    Ano = Table.AddColumn(DateWithColumns, "Ano", each Date.Year([Data])),
    Mês = Table.AddColumn(Ano, "Mês", each Date.Month([Data])),
    NomeMês = Table.AddColumn(Mês, "Nome do Mês", each Date.ToText([Data], "MMMM")),
    Dia = Table.AddColumn(NomeMês, "Dia", each Date.Day([Data])),
    DiaDaSemana = Table.AddColumn(Dia, "Dia da Semana", each Date.DayOfWeek([Data], Day.Monday)),
    NomeDiaDaSemana = Table.AddColumn(DiaDaSemana, "Nome do Dia da Semana", each Date.ToText([Data], "dddd")),
    Trimestre = Table.AddColumn(NomeDiaDaSemana, "Trimestre", each Date.QuarterOfYear([Data])),
    Semestre = Table.AddColumn(Trimestre, "Semestre", each if Date.Month([Data]) <= 6 then 1 else 2)
in
    Semestre